/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

/**
 *
 * @author angel
 */
public class FighterUI extends javax.swing.JPanel {

    /**
     * Creates new form FighterUI
     */
    public FighterUI() {
        initComponents();
        this.setOpaque(false);
        FighterCard.setText("");
        clearFightersLabels();
    }
    
    public void clearFightersLabels() {
        this.FighterCard.setIcon(null);
        this.characterIDLabel.setText("");
        this.HPLabel.setText("");
        this.StatusLabel.setText("Pendiente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FighterCard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        characterIDLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HPLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FighterCard.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FighterCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FighterCard.setText("FighterCard");
        add(FighterCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 220));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HP Actual");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 160, 40));

        StatusLabel.setBackground(new java.awt.Color(0, 0, 0));
        StatusLabel.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLabel.setText("Pendiente");
        add(StatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 160, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estado Actual");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 160, 40));

        characterIDLabel.setBackground(new java.awt.Color(0, 0, 0));
        characterIDLabel.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        characterIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        characterIDLabel.setText("jLabel2");
        add(characterIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PersonajeID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, 40));

        HPLabel.setBackground(new java.awt.Color(0, 0, 0));
        HPLabel.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        HPLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HPLabel.setText("jLabel2");
        add(HPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 160, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FighterCard;
    private javax.swing.JLabel HPLabel;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel characterIDLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the FighterCard
     */
    public javax.swing.JLabel getFighterCard() {
        return FighterCard;
    }

    /**
     * @return the HPLabel
     */
    public javax.swing.JLabel getHPLabel() {
        return HPLabel;
    }

    /**
     * @return the StatusLabel
     */
    public javax.swing.JLabel getStatusLabel() {
        return StatusLabel;
    }

    /**
     * @return the characterIDLabel
     */
    public javax.swing.JLabel getCharacterIDLabel() {
        return characterIDLabel;
    }
    
}
