/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Funciones.AudioManager;
import Funciones.ImageMovie;
import proyecto2.App;
import javax.swing.ImageIcon;
import javax.swing.JSlider;

/**
 *
 * @author author
 */
public class Home extends javax.swing.JFrame {
    
    private ImageMovie imageUtils = new ImageMovie();
    private AudioManager audioManager;
    App app = App.getInstance();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        //Seteo del audioManager
        this.audioManager = new AudioManager(); 
        audioManager.playMusic("/GUI/Assets/backgroundSound.wav");
        
        ImageIcon cartoonNetworkLogo = imageUtils.loadScaledImage("/GUI/Assets/StarWars/logo.png", 140, 80);
        ImageIcon nickelodeonLogo = imageUtils.loadScaledImage("/GUI/Assets/StarTrek/logo.png", 120, 80);
        
        starWarsPeleador.getLogo().setIcon(cartoonNetworkLogo);
        starTrekPeleador.getLogo().setIcon(nickelodeonLogo);
        starWarsPeleador.getLogo().setText("");
        starTrekPeleador.getLogo().setText("");
        iaStatusLabel.setText("");
        WinnerLabelID.setText("");
        
        // Se setean las imagenes que la lucha en la IA.
        //ImageIcon regularShowCardIA=  imageUtils.loadScaledImage(app.getIaArena().getRegularShowFighter().getUrlSource(), 150, 200);
        //this.StarWarsCard.setIcon(regularShowCardIA);
        //ImageIcon avatarCardIA=  imageUtils.loadScaledImage(app.getIaArena().getAvatarFighter().getUrlSource(), 150, 200);
        //this.StarTrek.setIcon(avatarCardIA);
        // Se configura el slider 
        battleDuration.setOpaque(false);
        battleDuration.setMinimum(1);
        battleDuration.setMaximum(20);
        battleDuration.setValue(App.getBattleDuration());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FightingTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        battleDuration = new javax.swing.JSlider();
        clockVelocity = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        WinnerLabelID = new javax.swing.JLabel();
        Winner1 = new javax.swing.JLabel();
        FigtherUI1 = new Interfaz.FighterUI();
        FigtherUI2 = new Interfaz.FighterUI();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        iaStatusLabel = new javax.swing.JLabel();
        roundLabel = new javax.swing.JLabel();
        starTrekPeleador = new Interfaz.TvPanelUI();
        starWarsPeleador = new Interfaz.TvPanelUI();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FightingTitle.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        FightingTitle.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle.setText("STAR WARS VS STAR TREK");
        jPanel1.add(FightingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 770, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        battleDuration.setBackground(new java.awt.Color(0, 255, 255));
        battleDuration.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        battleDuration.setMajorTickSpacing(9);
        battleDuration.setMaximum(20);
        battleDuration.setMinimum(1);
        battleDuration.setMinorTickSpacing(1);
        battleDuration.setPaintLabels(true);
        battleDuration.setPaintTicks(true);
        battleDuration.setToolTipText("Slider de Velocidad");
        battleDuration.setValue(10);
        battleDuration.setOpaque(true);
        battleDuration.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                battleDurationStateChanged(evt);
            }
        });
        battleDuration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                battleDurationMouseClicked(evt);
            }
        });

        clockVelocity.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        clockVelocity.setForeground(new java.awt.Color(0, 0, 51));
        clockVelocity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockVelocity.setText("VELOCIDAD DE PELEA EN SEGUNDOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(battleDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(clockVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(battleDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));

        WinnerLabelID.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        WinnerLabelID.setForeground(new java.awt.Color(255, 255, 255));
        WinnerLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinnerLabelID.setText("Ganador");

        Winner1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        Winner1.setForeground(new java.awt.Color(255, 255, 255));
        Winner1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Winner1.setText("VICTORIA:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Winner1)
                .addGap(18, 18, 18)
                .addComponent(WinnerLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Winner1)
                    .addComponent(WinnerLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/vsImagenPelea.jpg"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setForeground(new java.awt.Color(0, 51, 51));

        iaStatusLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        iaStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        iaStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iaStatusLabel.setText("IA STATUS LABEL");
        iaStatusLabel.setToolTipText("");

        roundLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        roundLabel.setForeground(new java.awt.Color(255, 255, 255));
        roundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundLabel.setText("RONDA: 0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(roundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iaStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iaStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundLabel)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(FigtherUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FigtherUI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FigtherUI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FigtherUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 520, 740));
        jPanel1.add(starTrekPeleador, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, -1, -1));
        jPanel1.add(starWarsPeleador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPeleaBueno.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void battleDurationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_battleDurationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_battleDurationMouseClicked

    private void battleDurationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_battleDurationStateChanged
        // TODO add your handling code here:
        int newSpeed = getBattleDuration().getValue();
        //        app.getIaArena().setCombatSpeed(newSpeed);
    }//GEN-LAST:event_battleDurationStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FightingTitle;
    private Interfaz.FighterUI FigtherUI1;
    private Interfaz.FighterUI FigtherUI2;
    private javax.swing.JLabel Winner1;
    private javax.swing.JLabel WinnerLabelID;
    private javax.swing.JSlider battleDuration;
    private javax.swing.JLabel clockVelocity;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iaStatusLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel roundLabel;
    private Interfaz.TvPanelUI starTrekPeleador;
    private Interfaz.TvPanelUI starWarsPeleador;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tvPanelUI1
     */
    public Interfaz.TvPanelUI getTvPanelUI1() {
        return starWarsPeleador;
    }

    /**
     * @return the tvPanelUI2
     */
    public Interfaz.TvPanelUI getTvPanelUI2() {
        return starTrekPeleador;
    }

    /**
     * @return the avatarFighter
     */
    public Interfaz.FighterUI getAvatarFighter() {
        return FigtherUI2;
    }

    /**
     * @return the regularShowFighter
     */
    public Interfaz.FighterUI getRegularShowFighter() {
        return FigtherUI1;
    }

    /**
     * @return the iaStatusLabel
     */
    public javax.swing.JLabel getIaStatusLabel() {
        return iaStatusLabel;
    }

    /**
     * @return the WinnerLabelID
     */
    public javax.swing.JLabel getWinnerLabelID() {
        return WinnerLabelID;
    }

    /**
     * @return the roundLabel
     */
    public javax.swing.JLabel getRoundLabel() {
        return roundLabel;
    }

    /**
     * @return the battleDuration
     */
    public javax.swing.JSlider getBattleDuration() {
        return battleDuration;
    }
}
