/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Funciones.Cola;
import javax.swing.JLabel;

/**
 *
 * @author sisir
 */
public class TvPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form TvPanelUI
     */
    public TvPanelUI() {
        initComponents();
        this.getQueueUI1().getTitleQueueUI().setText("COLA ALTA PRIORIDAD");
        this.getQueueUI2().getTitleQueueUI().setText("COLA MEDIA PRIORIDAD");
        this.getQueueUI3().getTitleQueueUI().setText("COLA BAJA PRIORIDAD");
        this.getQueueUI4().getTitleQueueUI().setText("COLA DE REFUERZO");
    }

    public void updateUIQueue(Cola queue1, Cola queue2, Cola queue3, Cola queue4) {
        this.Cola1.updateQueueUI(queue1);
        this.Cola2.updateQueueUI(queue2);
        this.Cola3.updateQueueUI(queue3);
        this.ColaRefuerzo.updateQueueUI(queue4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartoonNetworkLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Cola1 = new Interfaz.QueueUI();
        Cola2 = new Interfaz.QueueUI();
        Cola3 = new Interfaz.QueueUI();
        ColaRefuerzo = new Interfaz.QueueUI();
        logo = new javax.swing.JLabel();
        victoriesLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        cartoonNetworkLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartoonNetworkLogo.setText("cartoonNetworkLogo");

        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Cola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));
        jPanel1.add(Cola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));
        jPanel1.add(Cola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel1.add(ColaRefuerzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("TVLogo");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 100));

        victoriesLabel.setBackground(new java.awt.Color(255, 255, 255));
        victoriesLabel.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        victoriesLabel.setForeground(new java.awt.Color(255, 255, 255));
        victoriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victoriesLabel.setText("0");
        jPanel1.add(victoriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 50, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Broadway", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VICTORY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBatalla.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 380, 740));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 740));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Interfaz.QueueUI Cola1;
    private Interfaz.QueueUI Cola2;
    private Interfaz.QueueUI Cola3;
    private Interfaz.QueueUI ColaRefuerzo;
    private javax.swing.JLabel cartoonNetworkLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel victoriesLabel;
    // End of variables declaration//GEN-END:variables

    public JLabel getLogo() {
        return this.logo;
    }

    public QueueUI getQueueUI1() {
        return this.Cola1;
    }

    public QueueUI getQueueUI2() {
        return this.Cola2;
    }

    public QueueUI getQueueUI3() {
        return this.Cola3;
    }

    public QueueUI getQueueUI4() {
        return this.ColaRefuerzo;
    }

    /**
     * @return the victoriesLabel
     */
    public javax.swing.JLabel getVictoriesLabel() {
        return victoriesLabel;
    }

}
